name: AWS Lambda Function Testing Workflow

on:
  workflow_call:
    inputs:
      component-path:
        description: 'Path to the component to test'
        required: true
        type: string
      component-name:
        description: 'Name of the component'
        required: true
        type: string
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.12'
        type: string

jobs:
  test:
    name: Test ${{ inputs.component-name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create virtual environment
        working-directory: ${{ inputs.component-path }}
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: ${{ inputs.component-path }}
        run: |
          source .venv/bin/activate
          make install-dev
          make install-test-deps

      - name: Run linting
        working-directory: ${{ inputs.component-path }}
        run: |
          source .venv/bin/activate
          make format-check

      - name: Run unit tests
        working-directory: ${{ inputs.component-path }}
        run: |
          source .venv/bin/activate
          make test

      - name: Run integration tests
        working-directory: ${{ inputs.component-path }}
        run: |
          source .venv/bin/activate
          make integration-test-setup
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
