name: AWS Lambda Function Testing Workflow

on:
  workflow_call:
    inputs:
      component-path:
        description: 'Path to the component to test'
        required: true
        type: string
      component-name:
        description: 'Name of the component'
        required: true
        type: string
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.12'
        type: string

jobs:
  test:
    name: Test ${{ inputs.component-name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install development dependencies
        run: gradle :${{ inputs.component-name }}:installDevDependencies

      - name: Run code formatting and linting checks
        run: gradle :${{ inputs.component-name }}:formatCheck :${{ inputs.component-name }}:lint

      - name: Run unit tests with coverage
        run: gradle :${{ inputs.component-name }}:test

      - name: Run integration tests
        run: gradle :${{ inputs.component-name }}:integrationTest
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
